DROP TABLE IF EXISTS bowling_scorecards CASCADE;
DROP TABLE IF EXISTS batting_scorecards CASCADE;
DROP TABLE IF EXISTS deliveries CASCADE;
DROP TABLE IF EXISTS innings CASCADE;
DROP TABLE IF EXISTS match_players CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS team_players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS player_stats CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS match_status CASCADE;
DROP TYPE IF EXISTS toss_decision CASCADE;
DROP TYPE IF EXISTS batting_style CASCADE;
DROP TYPE IF EXISTS extra_type CASCADE;
DROP TYPE IF EXISTS wicket_type CASCADE;